# Generated by Django 5.1.1 on 2025-02-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_started', models.DateTimeField(blank=True, null=True)),
                ('dt_finished', models.DateTimeField(blank=True, null=True)),
                ('complexity', models.PositiveIntegerField(default=10)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Running'), (2, 'Finished'), (3, 'Error')], default=0)),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-dt_created'],
            },
        ),
    ]
